version: "3.9"

services:
  db:
    image: postgres:15
    container_name: log430-postgres
    restart: always
    environment:
      POSTGRES_DB: magasin
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    build: .
    container_name: log430-app
    depends_on:
      - db
    environment:
      POSTGRES_DB: magasin
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  postgres-data:
