global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'fastapi'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8000']

  - job_name: 'nginx'
    metrics_path: /metrics
    static_configs:
      - targets: ['nginx-exporter:9113']

  - job_name: 'stock-service-1'
    metrics_path: /metrics
    static_configs:
      - targets: ['stock-service-1:8000']

  - job_name: 'stock-service-2'
    metrics_path: /metrics
    static_configs:
      - targets: ['stock-service-2:8000']

