global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'fastapi'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8000']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
